# Generated by Django 4.2.3 on 2023-08-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cateogary', '0005_alter_cateogary_is_active'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cateogary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cateogary.cateogary'),
        ),
    ]
