# Generated by Django 4.2.3 on 2023-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cateogary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogary_name', models.CharField(max_length=50, unique=True)),
                ('discription', models.TextField(max_length=100)),
                ('cateogary_image', models.ImageField(blank=True, null=True, upload_to='photos/cateogaries')),
            ],
            options={
                'verbose_name': 'cateogarie',
            },
        ),
    ]
