# Generated by Django 4.2.3 on 2023-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cateogary', '0004_cateogary_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateogary',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
