# Generated by Django 4.2.3 on 2023-08-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('cateogary', '0005_alter_cateogary_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateogary',
            name='offerr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
    ]
