# Generated by Django 4.2.3 on 2023-08-15 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0001_initial'),
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder_item',
            name='variation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='variation.variation'),
            preserve_default=False,
        ),
    ]
