# Generated by Django 4.2.3 on 2023-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_oreder_item_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder_item',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
