# Generated by Django 4.2.3 on 2023-09-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0005_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
