# Generated by Django 4.2.3 on 2023-09-01 08:02

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(validators=[offers.models.validate_expiry_date]),
        ),
    ]
