# Generated by Django 4.2.3 on 2023-09-01 09:03

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(validators=[offers.models.validate_end_date]),
        ),
    ]
