# Generated by Django 4.2.3 on 2023-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('is_expired', models.BooleanField(default=False)),
                ('discout_price', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
